### PR TITLE
Conform to Vultr's rate limit of 2 req/s

### PR DESCRIPTION
**Pull request by teh-username**
Updated PR for #9. Closes issue #8.

### CODE REVIEW

**Comment by teh-username** [comment]
Did some digging and it looks like issue has been a problem [for a while now](https://github.com/hashicorp/terraform/issues/1051). One potential workaround is for the provider to [handle it directly](https://www.terraform.io/docs/internals/graph.html#walking-the-graph).

Sounds like a potential feature down the pipeline.

**Comment by squat** [comment]
@teh-username thanks for digging into this. Can you squash the two commits? After that LGTM and we can merge

**Comment by squat** [comment]
Fixes #8

**Comment by squat** [comment]
Thanks very much, @teh-username!

**Comment by teh-username** [comment]
Cheers @squat!

**Pull request merged**
