### PR TITLE
Build updates

### PR DESCRIPTION
**Pull request by danielsreichenbach**
This resolves a small issue with dependencies and updates the build system to be in line with what official Terraform providers use.

- Terraform version is fixed to v0.10.0 in `glide.yaml`
- Travis build is now in sync with official TF providers:
  - scripts added to help with `go get`
  - Makefile now will `build` by default
  - few options for vetting, etc. updated
- README updated to match changes

### CODE REVIEW

**Comment by danielsreichenbach** [comment]
This is basically intended to help getting #5 done, I'll open PRs for documentation (as in website component for TF providers) and Acceptance tests soonish.

**Comment by squat** [comment]
@danielsreichenbach thanks so much for this contribution and sorry I let it get stale. Any chance you could rebase the PR on top of master so we could review and merge?

**Comment by danielsreichenbach** [comment]
No worries, I’ve been that guy myself 😅

I will rebase tonight and push an updated version.

**Comment by squat** [comment]
Thanks Daniel. There’s no hurry for this, since we still need acceptance tests anyways, I just don’t want to leave it hanging!

**Pull request closed without merging**
